---
repos:
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.40.0
  - hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-encoding-pragma
      - id: detect-private-key
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 22.10.0
  - hooks:
      - additional_dependencies:
          - black==22.12.0
        id: blacken-docs
    repo: https://github.com/adamchainz/blacken-docs
    rev: v1.12.1
  - hooks:
      - id: reorder-python-imports
    repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
  - hooks:
      - id: pycln
    repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
